jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      env:
        JAVA_OPTS: -Xmx2048m
        TERM: dumb
      run: ./gradlew --no-daemon build
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
