jobs:
  test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: fsfe/reuse-action@v1
name: REUSE Compliance Check
on:
  repository_dispatch:
    types: trigger-ga___reuse.yml
